import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:intl/intl.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../entities/transaction_entity.dart';
import '../entities/transaction_type.dart';
import '../entities/transaction_category.dart';

class ExportTransactionsPdf {
  Future<void> call(
    List<TransactionEntity> transactions,
    String userName,
    String currencySymbol,
  ) async {
    if (transactions.isEmpty) return;

    debugPrint(
      'Generating PDF report for ${transactions.length} transactions...',
    );

    final logoBytes = await rootBundle.load('assets/images/logo.png');
    final logoImage = pw.MemoryImage(logoBytes.buffer.asUint8List());

    final pdf = pw.Document();

    // Sort transactions by date descending
    final sorted = List<TransactionEntity>.from(transactions)
      ..sort((a, b) => b.date.compareTo(a.date));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              padding: const pw.EdgeInsets.only(bottom: 12),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Row(
                    children: [
                      pw.Image(logoImage, width: 44, height: 44),
                      pw.SizedBox(width: 12),
                      pw.Column(
                        crossAxisAlignment: pw.CrossAxisAlignment.start,
                        children: [
                          pw.Text(
                            'Finn',
                            style: pw.TextStyle(
                              fontSize: 24,
                              fontWeight: pw.FontWeight.bold,
                              color: PdfColors.blueGrey900,
                            ),
                          ),
                          pw.Text(
                            'Transactions Report',
                            style: const pw.TextStyle(
                              fontSize: 12,
                              color: PdfColors.blueGrey,
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        DateFormat('MMM dd, yyyy').format(DateTime.now()),
                        style: const pw.TextStyle(fontSize: 10),
                      ),
                      pw.Text(
                        'User: $userName',
                        style: pw.TextStyle(
                          fontSize: 10,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 24),
            pw.TableHelper.fromTextArray(
              headers: ['Date', 'Category', 'Type', 'Amount', 'Notes'],
              data: sorted.map((t) {
                return [
                  DateFormat('yyyy-MM-dd').format(t.date),
                  t.category.label,
                  t.type == TransactionType.income ? 'Income' : 'Expense',
                  '$currencySymbol${t.amount.toStringAsFixed(2)}',
                  t.notes ?? '',
                ];
              }).toList(),
              border: null,
              headerStyle: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.blueGrey800,
              ),
              cellHeight: 30,
              cellAlignments: {
                0: pw.Alignment.centerLeft,
                1: pw.Alignment.centerLeft,
                2: pw.Alignment.center,
                3: pw.Alignment.centerRight,
                4: pw.Alignment.centerLeft,
              },
            ),
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 24),
              child: pw.Divider(),
            ),
            pw.Text(
              'Report generated by Finn - Your Personal Money Companion',
              style: const pw.TextStyle(color: PdfColors.grey700, fontSize: 10),
            ),
          ];
        },
      ),
    );

    final directory = await getTemporaryDirectory();
    final fileName = 'finn_report_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final filePath = p.join(directory.path, fileName);
    final file = File(filePath);

    await file.writeAsBytes(await pdf.save(), flush: true);
    debugPrint('PDF file written to: $filePath');

    await SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path, mimeType: 'application/pdf')],
        subject: 'My Finn Transactions PDF Report',
      ),
    );
  }
}
